version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "🔧 [APP] Début de l'installation"
      - mvn --version

      - echo "Connexion à ECR"
      - aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 116981792309.dkr.ecr.eu-west-3.amazonaws.com

      - echo "📦 [INFRA] Installation de Terraform..."
      - curl -s -o terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip -o terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version

  pre_build:
    commands:
      - echo "🔨 [APP] Vérifie si le repo ECR existe..."
      - |
        aws ecr describe-repositories --repository-names petclinic --region eu-west-3 || \
        aws ecr create-repository --repository-name petclinic --region eu-west-3

      - echo "🔐 [INFRA] Connexion à AWS"
      - aws sts get-caller-identity

  build:
    commands:
      - echo "🔨 [APP] Compilation et Dockerisation intelligente des microservices"
      - chmod +x push-ecr.sh
      - ./push-ecr.sh

      - echo "⚙️ [INFRA] Initialisation de Terraform..."
      - cd terraform-config
      - terraform init

      - echo "🔄 [INFRA] Synchronisation avec l'état distant"
      - terraform refresh

      - echo "📦 [INFRA] Planification de l'infrastructure..."
      - terraform plan -out=tfplan

      - echo "🚀 [INFRA] Déploiement de l'infrastructure..."
      - terraform apply -auto-approve tfplan

  post_build:
    commands:
      - echo "✅ [INFRA] Déploiement terminé"
      - echo "📤 [INFRA] Outputs de l'infrastructure"
      - cd terraform-config
      - terraform output

artifacts:
  files:
    - '**/*'

