version: 0.2

env:
  variables:
    CLUSTER_NAME: "petclinic-eks"
    REGION: "eu-west-3"

phases:
  install:
    commands:
      - echo "🔧 Installation de kubectl"
      - curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.16/2024-09-11/bin/linux/amd64/kubectl
      - chmod +x kubectl && mv kubectl /usr/local/bin/kubectl
      - echo "✅ kubectl installé"

  pre_build:
    commands:
      - echo "📡 Connexion au cluster"
      - aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME

      - echo "🔐 Vérification des accès kubectl"
      - kubectl get nodes || { echo "❌ Échec de l'accès au cluster EKS. Vérifiez les permissions IAM."; exit 1; }

  build:
    commands:
      - echo "🚀 Création du namespace si besoin"
      - kubectl create namespace petclinic || echo "Namespace petclinic existe déjà"
      - echo "🚀 Déploiement des ressources Kubernetes"
      - kubectl apply -f k8s-manifests/ -n petclinic
      - echo "🌐 Vérification de l'Ingress"
      - kubectl get ingress -n petclinic
      - echo "📡 Adresse IP publique de l'Ingress :"
      - kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'

artifacts:
  files:
    - '**/*'
