version: 0.2

phases:
  install:
    commands:
      - echo "🔧 Configuration de l'accès au cluster"
      - aws eks --region eu-west-3 update-kubeconfig --name petclinic-eks

  build:
    commands:
      - echo "🚀 Création du namespace si besoin"
      - kubectl create namespace petclinic || echo "Namespace petclinic existe déjà"
      - echo "🚀 Déploiement des ressources Kubernetes"
      - kubectl apply -f k8s-manifests/ -n petclinic
      - echo "🌐 Vérification de l'Ingress"
      - kubectl get ingress -n petclinic
      - echo "📡 Adresse IP publique de l'Ingress :"
      - kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'

artifacts:
  files:
    - '**/*'
