version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "🔧 [APP] Début de l'installation"
      - mvn --version
      - echo "Connexion à ECR"
      - aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 116981792309.dkr.ecr.eu-west-3.amazonaws.com
      - echo "📦 [INFRA] Installation de Terraform..."
      - curl -s -o terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip -o terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version

  pre_build:
    commands:
      # Partie APP
      - echo "🔨 [APP] Vérifie si le repo ECR existe..."
      - |
        aws ecr describe-repositories --repository-names petclinic --region eu-west-3 || \
        aws ecr create-repository --repository-name petclinic --region eu-west-3
      # Partie INFRA
      - echo "🔐 [INFRA] Connexion à AWS ECR pour récupérer les permissions"
      - aws sts get-caller-identity
      - cd terraform-config

  build:
    commands:
      # Partie APP
      - echo "🔨 [APP] Compilation et Dockerisation de chaque microservice"
      - cd ..
      - chmod +x push-ecr.sh
      - ./push-ecr.sh
      # Partie INFRA
      - cd terraform-config
      - echo "⚙️ [INFRA] Initialisation de Terraform..."
      - terraform init
      - echo "📦 [INFRA] Planification de l'infrastructure..."
      - terraform plan
      - echo "🚀 [INFRA] Déploiement de l'infrastructure..."
      - terraform apply -auto-approve

  post_build:
    commands:
      - cd terraform-config
      - echo "✅ [INFRA] Terraform apply terminé"
      - echo "📤 [INFRA] Export des outputs utiles..."
      - terraform output

artifacts:
  files:
    - '**/*'
