version: 0.2

phases:
  install:
    commands:
      - echo "📦 Installation de Terraform..."
      - curl -s -o terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip -o terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version
  pre_build:
    commands:
      - echo "🔐 Connexion à AWS ECR pour récupérer les permissions"
      - aws sts get-caller-identity
      - cd terraform
  build:
    commands:
      - echo "⚙️ Initialisation de Terraform..."
      - terraform init
      - echo "📦 Planification de l'infrastructure..."
      - terraform plan
      - echo "🚀 Déploiement de l'infrastructure..."
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "✅ Terraform apply terminé"
      - echo "📤 Export des outputs utiles..."
      - terraform output

artifacts:
  files:
    - '**/*'
