version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "🔧 Début de l'installation"
      - mvn --version
      - echo "Connexion à ECR"
      - aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 116981792309.dkr.ecr.eu-west-3.amazonaws.com
  build:
    commands:
      - echo "🔨 Vérifie si le repo ECR existe..."
      - |
        aws ecr describe-repositories --repository-names petclinic --region eu-west-3 || \
        aws ecr create-repository --repository-name petclinic --region eu-west-3
      - echo "🔨 Compilation et Dockerisation de chaque microservice"
      - chmod +x push-ecr.sh
      - ./push-ecr.sh
