version: 0.2

phases:
install:
  commands:
    - echo "🔧 Installation de kubectl et configuration de l'accès au cluster"
    - curl -LO https://amazon-eks.s3.eu-west-3.amazonaws.com/1.27.16/2024-03-20/bin/linux/amd64/kubectl
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
    - kubectl version --client
    - aws eks --region eu-west-3 update-kubeconfig --name petclinic-eks

  build:
    commands:
      - echo "🚀 Déploiement des ressources Kubernetes"
      - kubectl apply -f k8s-manifests/ -n petclinic
      - echo "🌐 Vérification de l'Ingress"
      - kubectl get ingress -n petclinic
      - echo "📡 Adresse IP publique du contrôleur Ingress :"
      - kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
artifacts:
  files:
    - '**/*'
