apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vets-service-ingress
  namespace: petclinic
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /vets
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/vet
            pathType: Prefix
            backend:
              service:
                name: vets-service
                port:
                  number: 8083
